version: '3.8'

services:
  backend:
    image: romanca/trello-clone-backend:dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 

  frontend:
    image: romanca/trello-clone-front:dev
    ports:
      - "3000:3000"
    environment:
      - VITE_PORT=3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 

  # watchtower:
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=1
  #   restart: always
