version: '3.8'

services:
  backend:
    image: romanca/trello-clone-backend:dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://rjamrisko:Zk0cSHXVaG2Sqkmb@cluster0.q6xa5.mongodb.net/dbname?retryWrites=true&w=majority

  frontend:
    image: romanca/trello-clone-front:dev
    ports:
      - "3000:3000"
    environment:
      - VITE_PORT=3000
