name: Build and Deploy Docker Image

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image for Development
        uses: docker/build-push-action@v4
        with:
          context: . 
          push: true
          tags: romanca/trello-clone-front:dev
          file: Dockerfile.dev


      - name: Build and push Docker image for Production
        uses: docker/build-push-action@v4
        with:
          context: . 
          push: true
          tags: romanca/trello-clone-front:prod
          file: Dockerfile.prod

      - name: Notify on success
        run: echo "Docker images for both Development and Production have been built and pushed successfully!"
